[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.46"

[context.production.environment]
HUGO_BASEURL = "https://ewis.netlify.com"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --enableGitInfo -b $DEPLOY_PRIME_URL"
